schema {
  query: Query
  mutation: Mutation
}

type Query {
  GetAllStories(): [Story!]!
  GetOddStories(): [Story!]!
  GetEvenStories(): [Story!]!
}

type Mutation {
  CreateStory(title: String!): Story!
}

type Story {
  id:  ID!
  title: String!
}

